controller_list:
  - name: fake_aubo_arm_controller
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  - name: fake_gripper_controller
    joints:
      - gripper_finger1_joint